#!/bin/bash
clear
echo""

echo -e '\e[92m'

echo '

	███ █   █ ███ ███ ███ █   █   ███ █   █ ███
	 █  ██  █ █    █  █ █ █   █    █  ██  █ █
	 █  █ █ █  █   █  █ █ █   █    █  █ █ █ █
	 █  █  ██   █  █  ███ █   █    █  █  ██ █ █
	███ █   █ ███  █  █ █ ███ ███ ███ █   █ ███ █ █  '

echo ""
	apt update
echo ""
	apt upgrade
echo ""
	apt -y install ruby
echo ""
	gem -y install lolcat
echo ""
	apt -y install figlet
echo ""
	apt -y install unzip
echo ""
	unzip db.zip
echo ""
	rm db.zip
echo ""
	apt -y install cowsay
echo ""
	chmod +x TXB.sh
echo ""

clear

echo ""

echo -e '\e[92m`````````````````````````````````````````````````'

echo ""

echo " Installation completed " | lolcat

echo ""

echo -e '\e[92m`````````````````````````````````````````````````'

echo ""

echo ' run $ bash TXB.sh '

echo ""

echo ""
